name: "Eylu"
markdown: redcarpet
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile]

# Information for the Atom feed
eylu:
  author: "Wang eylu"
  email: "eylu@github.com"
